name: NBA Full Slate Projections

on:
  schedule:
    - cron: "0 21 * * *"   # daily @ 4 PM EST
  workflow_dispatch:

jobs:
  run-nba-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run NBA model
        run: |
          python master_projection_engine.py
